# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2022-2025, PyMC Labs
# This file is distributed under the same license as the pymc-marketing
# package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pymc-marketing local\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-07 18:10+0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: es\n"
"Language-Team: es <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: ../source/api/generated/classmethods/pymc_marketing.mmm.budget_optimizer.BudgetOptimizer.__init__.rst:2
#: 1099fa18cbe64b818aa2c6514669b276
msgid "BudgetOptimizer.\\_\\_init\\_\\_"
msgstr ""

#: d8e656d5bfbd422786cb3c7c9c4d7bef of
#: pymc_marketing.mmm.budget_optimizer.BudgetOptimizer.__init__:2
msgid ""
"Create a new model by parsing and validating input data from keyword "
"arguments."
msgstr ""

#: a14bc0b0b47c43f89b0d75243525b4c7 of
#: pymc_marketing.mmm.budget_optimizer.BudgetOptimizer.__init__:4
msgid ""
"Raises [`ValidationError`][pydantic_core.ValidationError] if the input "
"data cannot be validated to form a valid model."
msgstr ""

#: f863cf8e5c654b879718874e8b7b4879 of
#: pymc_marketing.mmm.budget_optimizer.BudgetOptimizer.__init__:7
msgid "`self` is explicitly positional-only to allow `self` as a field name."
msgstr ""
